### ISSUE TITLE
Upgrade to libc 0.2

### ISSUE THREAD

**Issue by frewsxcv** [energymon/energymon-sys#6]

**Comment by connorimes** [comment]
I'm getting this warning after upgrading the `libc` dependency.  The same occurs in each of the -sys binding crates that implement a particular function prototype that accepts a `size_t`.  Is this a bug in the `libc` crate?

<pre>
$ cargo build
   Compiling libc v0.2.2
   Compiling pkg-config v0.3.6
   Compiling energymon-sys v0.1.0 (file:///local/energymon-sys/energymon-dummy-sys)
   Compiling energymon-dummy-sys v0.1.0 (file:///local/energymon-sys/energymon-dummy-sys)
lib.rs:16:63: 16:69 warning: found type without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(...)] attribute to the type, #[warn(improper_ctypes)] on by default
lib.rs:16     pub fn energymon_get_source_dummy(buffer: *mut c_char, n: size_t) -> *mut c_char;
                                                                        ^~~~~~
</pre>

**Comment by connorimes** [comment]
After some research, this warning should be fixed in 1.5 beta - see rust-lang/rust/pull/28779

**Comment by connorimes** [comment]
Fixed in c2e0b01.
